// Generated by CoffeeScript 1.6.2
(function() {
  window.addEventListener("load", function() {
    return document.getElementById("close").onclick = function() {
      return window.close();
    };
  });

}).call(this);
