// Generated by CoffeeScript 1.6.2
(function() {
  window.onload = function() {
    var main;

    if (TSMusic.test()) {
      main = new TSMusic.Main;
      main.plug(new TSMusic.FilePlugin);
      if (typeof chrome !== "undefined" && chrome.tabs) {
        main.plug(new TSMusic.XiaMiPlugin);
      }
      main.plug(new TSMusic.LyricPlugin);
      return main.plug(new TSMusic.SpectrumPlugin);
    } else {
      return alert("您的浏览器不支持此应用！");
    }
  };

}).call(this);
